version: '3.8'

services:

  app:
    build:
      context: .
    restart: always
    container_name: document_app
    command: ["scripts/migrate.sh"]
    ports:
      - "7500:8000"
    volumes:
      - ./documents:/documents/
    security_opt:
      - apparmor=unconfined
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16.2-alpine
    container_name: db_app
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docs_manager
    volumes:
      - .postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "docs_manager", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: .
    container_name: celery_app
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - ./documents:/documents/
    depends_on:
      - rabbitmq


  migrate:
    build:
      context: .
    restart: on-failure
    container_name: alembic_app
    command: alembic upgrade head
    depends_on:
      - db
      - app